### ISSUE TITLE
 @PreDestroy and @Singleton

### ISSUE THREAD

**Issue by gembin** [mycila/guice#5]
why @PreDestroy method is only called when a bean is annotated with @Singleton?

**Comment by vasigorc** [comment]
Could you create something like `@MycilaSessionScope` and in the custom scope pass session references to a `@Singleton` bean which would check when a Session is invalidated? 

e.g.:
```try {
  long sd = session.getCreationTime();
} catch (IllegalStateException ise) {
  // it's invalid
}```
from: http://stackoverflow.com/questions/634929/how-to-check-if-a-session-is-invalid

**Comment by mathieucarbou** [comment]
@vasigorc : please provide a PR if you have an idea about how to implement this because I clearly do not see, plus it would link the implementation to a session mechanism (I think you speak about HttpSession right ?)

**Comment by vasigorc** [comment]
Yes. 

> and in the custom scope pass session
If I will come-up with a solution I will be happy to help. But this, I now realise, won't work because a class declaring custom scope is just a set of rules it is not in any context. Sorry for that. 

I was also thinking about sth like this, but this won't work either. Checking all sessions in a big system in an interval is unrealistic and when it is evaluated the bean itself may be already cleaned by GC:
```
bindListener(Matchers.annotatedWith(MycillaSessionScope.class), new InjectionListener<I>() {
            @Override
            public void afterInjection(Object i) {
                SessionClass m = (SessionClass) i;
                //inject HttpServletRequest
                //get HttpSession and put in a map inside the listener 
            }
        });
```
